[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libefaturas"
description = "Biblioteca para uso do serviço e-fatura da Autoridade Tributária Portuguesa"
readme = "README.md"
authors = [
  { name = "Glie", email = "info@glie.ai" }
]
license = { text = "MIT" }
requires-python = ">=3.9"
dynamic = ["version"]
dependencies = [
  "cryptography>=42.0.0",
  "requests>=2.31.0"
]

[project.urls]
Homepage = "https://github.com/glieai/libefaturas"
Repository = "https://github.com/glieai/libefaturas"
[project.scripts]
libefaturas-cli = "libefaturas.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["libefaturas*"]

[tool.setuptools.dynamic]
version = { attr = "libefaturas.__about__.__version__" }
