[metadata]
name = libefaturas
version = 0.1.0
description = Biblioteca para uso do serviço e-fatura da Autoridade Tributária Portuguesa
long_description = file: README.md
long_description_content_type = text/markdown
author = Glie
author_email = info@glie.ai
url = https://github.com/glieai/libefaturas
project_urls =
    Homepage = https://github.com/glieai/libefaturas
    Repository = https://github.com/glieai/libefaturas
license = MIT
classifiers =
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Operating System :: OS Independent

[options]
packages = find:
package_dir =
    = src
python_requires = >=3.9
install_requires =
    cryptography>=42.0.0
    requests>=2.31.0
include_package_data = True

[options.packages.find]
where = src
include = libefaturas*

[options.entry_points]
console_scripts =
    libefaturas-cli = libefaturas.cli:main
