"""API pública exposta pelo pacote ``libefaturas``."""

from .__about__ import __version__
from .client import EFaturasClient, test_connection
from .security import EFaturasCredentials, UsernameToken
from .faturas import (
    ChannelInfo,
    DateRange,
    RegisterInvoiceInput,
    ChangeInvoiceStatusInput,
    DeleteInvoiceInput,
    RegisterWorkInput,
    ChangeWorkStatusInput,
    DeleteWorkInput,
    RegisterPaymentInput,
    ChangePaymentStatusInput,
    DeletePaymentInput,
    OperationResponse,
    FaturasError,
    FaturasService,
)
from .series import (
    CancelSeriesInput,
    CreateSeriesInput,
    FinalizeSeriesInput,
    OperationResult,
    Series,
    SeriesError,
    SeriesFilter,
    SeriesListResult,
    SeriesOperationResult,
    SeriesService,
)

__all__ = [
    "__version__",
    "EFaturasClient",
    "test_connection",
    "EFaturasCredentials",
    "UsernameToken",
    "ChannelInfo",
    "DateRange",
    "RegisterInvoiceInput",
    "ChangeInvoiceStatusInput",
    "DeleteInvoiceInput",
    "RegisterWorkInput",
    "ChangeWorkStatusInput",
    "DeleteWorkInput",
    "RegisterPaymentInput",
    "ChangePaymentStatusInput",
    "DeletePaymentInput",
    "OperationResponse",
    "FaturasError",
    "FaturasService",
    "CreateSeriesInput",
    "FinalizeSeriesInput",
    "CancelSeriesInput",
    "Series",
    "SeriesFilter",
    "OperationResult",
    "SeriesOperationResult",
    "SeriesListResult",
    "SeriesError",
    "SeriesService",
]
